test depoloyement on ec2

diff --git a/.github/workflow/cicd.yml b/.github/workflow/cicd.yml
--- a/.github/workflow/cicd.yml
+++ b/.github/workflow/cicd.yml
@@ -3,30 +3,36 @@ name: Deploy medsearch
 on:
   push:
     branches:
-      -main
+      - main
 
 jobs:
   build:
-    run-on: ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout Source
-        uses: action/checkout@v4
-      - name: create .env file
+        uses: actions/checkout@v4
+
+      - name: Create .env file
         run: echo "PORT=${{ secrets.PORT }}" >> .env
-      - name: login to docker hub
+
+      - name: Login to Docker Hub
         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-      - name: Build docker image
-        run: docker build -t gautamviki/medsearch-app .
-      - name: Push image to docker hub
+
+      - name: Build Docker Image
+        run: docker build -t gautamviki/medsearch-app:v1 .
+
+      - name: Push Image to Docker Hub
         run: docker push gautamviki/medsearch-app:v1
 
   deploy:
-    need: build
+    needs: build
     runs-on: self-hosted
-    steps: 
-      - name: pull the docker image
+    steps:
+      - name: Pull the Docker Image
         run: docker pull gautamviki/medsearch-app:v1
-      - name: delete the old container
-        run: docker rm -f go-app-container
-      - name: run docker container
-        run: docker run -d -p 3009:3009 --name go-app-container gautamviki/medsearch-app
+
+      - name: Delete Old Container
+        run: docker rm -f go-app-container || true  # Allow it to fail if the container doesn't exist
+
+      - name: Run Docker Container
+        run: docker run -d -p 3009:3009 --name go-app-container gautamviki/medsearch-app:v1
